### ISSUE TITLE
Loading repositories on demand when scrolling

### ISSUE THREAD

**Issue by jeroen** [twitter/opensource-website#14]
It would be really cool if the repo "pages" (100 repos per API call) were loaded as the user scrolls down, instead of loading them all at page load. Give a similar experience as [instagram](http://instagram.com/cashcats) or facebook or whatever.

I would like to use this template for an org that has 1500+ repositories, but currently it takes forever to load, and then you hit the github API limit :-) It would be cool to only load the first 100, and then dynamically add more when scrolling down the page.

**Comment by caniszczyk** [comment]
I'm all for contributions :)

**Comment by jeroen** [comment]
Are you OK with using jQuery plugins? E.g. http://imakewebthings.com/jquery-waypoints/

**Comment by caniszczyk** [comment]
Yep, it's under the MIT license so we're OK with it:
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt

**Comment by augbog** [comment]
If we decide to do this, how would we handle sorting? As of right now, I believe it sorts all the repos before showing them. If we pull data based on scroll, would we want it to resort them everytime?

**Comment by mbad0la** [comment]
@augbog @caniszczyk @jeroenooms Hey guys! I know this thread has been open for a really long time but i've recently started to explore github and try to contribute. Hence, i came upon this Repo and would like to help in this issue. Are you guys still interested in this?

About the issue, dont flame because im really a newbie :P 
But i went through the code and previous comments in this thread and i think we have two solutions -
1) Store the repo object and append next 30 or something repo data on detecting page end          ->  Though this method does implement the UI aspect of loading info after reaching the end of  the page, it defeats the purpose of avoiding rate limiting because as mentioned earlier for orgs with a huge amount of data, the user might not even go through all of it therefore, we have some wasted API calls.
2) Initiate api call to append next 30 or something repo data on detecting page end
->  This method implements the UI Element and helps optimisation of api calls but in the process we end up trading our hotness sorting functionality for this implementation. But we do have every 30 (or whatever threshold we set) repos sorted according to our hotness functionality.
A small deviation to this method can be to add every iterations' data to the repo list, sort the list again and then clear the "#repo" div and append the whole list into it again. Though this maintains the hotness sort and limits Api calls along with the UI functionality, it has a big flaw, of the user to miss out on some newly added repos if they attain positions for which user has to scroll up.

Please let me know what you think about this.
I'd like to submit a pull-request once we reach a conclusion.
