### ISSUE TITLE
I need a support, please help!

### ISSUE THREAD

**Issue by josephNg95** [twitter/opensource-website#80]
Please reply to this message as soon as you read it. I really need someone who can help!
thank you!

**Comment by josephNg95** [comment]
Sorry if this way bother you guys, I can't login my account and send many of many tickets, but I only received an automatic response message.
I can not connect with  twitter supporter directly, so I need to do this.

My account has two-layer security, so when I login I need a verify code. But, my network provider change the head of phone from (+84) 16 to (+84) 3 so I can not receive a verify code message.
I need someone can help me!
Please find some way can help. Thank you, thank you so much!

**Comment by decause** [comment]
@thuyettiensinh We're sorry to hear you're having trouble logging into your account, but GitHub issues are not monitored by our User Operations team for technical support. Might we suggest reading our dedicated help center articles related to your issue here, and DM'ing @TwitterSupport: https://twitter.com/TwitterSupport

https://help.twitter.com/en/managing-your-account/how-to-update-your-account-phone-number
https://help.twitter.com/en/managing-your-account
